import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#050111",
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: "#050111",
    padding: 12,
    gap: 10,
  },
  flex: {
    flex: 1,
  },
  bgBlobTop: {
    position: "absolute",
    top: -150,
    left: -90,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "#ff2ea6",
    opacity: 0.22,
  },
  bgBlobBottom: {
    position: "absolute",
    bottom: -180,
    right: -120,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: "#26c7ff",
    opacity: 0.2,
  },
  container: {
    paddingHorizontal: 14,
    paddingBottom: 34,
    paddingTop: 8,
    gap: 12,
  },
  panelHeader: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#332a64",
    backgroundColor: "rgba(11, 6, 28, 0.92)",
    padding: 12,
    gap: 12,
    shadowColor: "#ff3aa8",
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  brandLogo: {
    width: "100%",
    height: 170,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#3b2f71",
  },
  headerTextBlock: {
    gap: 4,
  },
  title: {
    color: "#f6edff",
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  subtitle: {
    marginTop: 3,
    color: "#89d0ff",
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  headerRowWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  serverBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#5f4f96",
    backgroundColor: "rgba(45, 35, 84, 0.7)",
    color: "#e8dcff",
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "700",
  },
  statusPill: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#24d8ff",
    backgroundColor: "rgba(36, 216, 255, 0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusPillError: {
    borderColor: "#ff4f9f",
    backgroundColor: "rgba(255, 79, 159, 0.15)",
  },
  statusText: {
    color: "#deffff",
    fontSize: 12,
    fontWeight: "700",
  },
  tabRow: {
    flexDirection: "row",
    gap: 8,
  },
  tabButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4a3d84",
    backgroundColor: "rgba(21, 14, 44, 0.94)",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  tabButtonOn: {
    borderColor: "#ff8ad2",
    backgroundColor: "rgba(255, 46, 166, 0.22)",
  },
  tabButtonText: {
    color: "#a9d7ff",
    fontSize: 13,
    fontWeight: "700",
  },
  tabButtonTextOn: {
    color: "#ffe7f8",
  },
  panel: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#30265f",
    backgroundColor: "rgba(10, 7, 26, 0.9)",
    padding: 12,
    gap: 10,
  },
  panelLabel: {
    color: "#9ad4ff",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.9,
    marginBottom: 2,
    fontWeight: "700",
  },
  serverTitle: {
    color: "#ffd5f1",
    fontSize: 15,
    fontWeight: "800",
  },
  serverSubtitle: {
    color: "#a7cfff",
    fontSize: 12,
  },
  serverListWrap: {
    gap: 8,
  },
  serverCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#44377a",
    backgroundColor: "rgba(18, 12, 40, 0.95)",
    padding: 10,
    gap: 8,
  },
  serverCardActive: {
    borderColor: "#2fd4ff",
    backgroundColor: "rgba(12, 25, 48, 0.88)",
  },
  serverCardHeader: {
    gap: 2,
  },
  serverName: {
    color: "#f4dfff",
    fontSize: 13,
    fontWeight: "800",
  },
  serverUrl: {
    color: "#93c8f7",
    fontSize: 11,
  },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3a2d71",
    backgroundColor: "rgba(14, 10, 34, 0.92)",
    color: "#f3ebff",
    paddingHorizontal: 11,
    paddingVertical: 10,
    fontSize: 15,
  },
  multilineInput: {
    minHeight: 86,
    textAlignVertical: "top",
  },
  modalInput: {
    minHeight: 110,
  },
  rowInlineSpace: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
  },
  switchLabel: {
    color: "#a6cfff",
    fontSize: 13,
    fontWeight: "600",
  },
  buttonPrimary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ff8ad2",
    paddingVertical: 11,
    paddingHorizontal: 12,
    backgroundColor: "#ff2ea6",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPrimaryText: {
    color: "#fff6fc",
    fontWeight: "800",
    fontSize: 14,
  },
  buttonGhost: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4a3d84",
    paddingVertical: 11,
    paddingHorizontal: 12,
    backgroundColor: "rgba(21, 14, 44, 0.94)",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonGhostText: {
    color: "#a9d7ff",
    fontWeight: "700",
    fontSize: 13,
  },
  flexButton: {
    flex: 1,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  formDivider: {
    height: 1,
    backgroundColor: "#3c316d",
    marginVertical: 4,
  },
  modeRow: {
    flexDirection: "row",
    gap: 8,
  },
  modeButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4a3d84",
    backgroundColor: "rgba(21, 14, 44, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  modeButtonOn: {
    borderColor: "#27d9ff",
    backgroundColor: "rgba(39, 217, 255, 0.16)",
  },
  modeButtonText: {
    color: "#a9d7ff",
    fontSize: 12,
    fontWeight: "700",
  },
  modeButtonTextOn: {
    color: "#defbff",
  },
  chipRow: {
    gap: 8,
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#47377e",
    backgroundColor: "rgba(24, 16, 49, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipActive: {
    borderColor: "#ff56b2",
    backgroundColor: "rgba(255, 86, 178, 0.18)",
  },
  chipText: {
    color: "#aad6ff",
    fontSize: 12,
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#ffe0f5",
  },
  terminalCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#342868",
    backgroundColor: "rgba(8, 6, 22, 0.95)",
    padding: 10,
    gap: 8,
    marginBottom: 8,
  },
  terminalHeader: {
    gap: 8,
  },
  terminalNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  terminalName: {
    color: "#ffd5f1",
    fontSize: 13,
    fontWeight: "800",
    flex: 1,
  },
  pillGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  modePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    overflow: "hidden",
  },
  modePillAi: {
    color: "#fff0f9",
    borderColor: "#ff6abf",
    backgroundColor: "rgba(255, 106, 191, 0.2)",
  },
  modePillShell: {
    color: "#defbff",
    borderColor: "#27d9ff",
    backgroundColor: "rgba(39, 217, 255, 0.16)",
  },
  livePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    overflow: "hidden",
  },
  livePillOn: {
    color: "#d5fffb",
    borderColor: "#27d9ff",
    backgroundColor: "rgba(39, 217, 255, 0.16)",
  },
  livePillOff: {
    color: "#ffdff4",
    borderColor: "#b66da0",
    backgroundColor: "rgba(182, 109, 160, 0.16)",
  },
  actionsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  actionButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#4b3f86",
    backgroundColor: "rgba(21, 14, 45, 0.95)",
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  actionButtonText: {
    color: "#9fd4ff",
    fontSize: 11,
    fontWeight: "700",
  },
  actionDangerButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ff5fae",
    backgroundColor: "rgba(255, 95, 174, 0.18)",
    paddingHorizontal: 9,
    paddingVertical: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  actionDangerText: {
    color: "#ffd4ee",
    fontSize: 11,
    fontWeight: "800",
  },
  terminalView: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#2fd4ff",
    backgroundColor: "#02010a",
    minHeight: 230,
    maxHeight: 360,
    padding: 9,
  },
  modalTerminalView: {
    flex: 1,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#2fd4ff",
    backgroundColor: "#02010a",
    padding: 10,
  },
  terminalText: {
    color: "#efe8ff",
    fontSize: 13,
    lineHeight: 18,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  modalHeader: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#35296b",
    backgroundColor: "rgba(12, 8, 30, 0.96)",
    padding: 10,
    gap: 8,
  },
  modalTitle: {
    color: "#f3dfff",
    fontSize: 15,
    fontWeight: "800",
  },
  emptyText: {
    color: "#8cb6db",
    fontSize: 13,
  },
});
