import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#050111",
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: "#050111",
    padding: 12,
    gap: 10,
  },
  flex: {
    flex: 1,
  },
  bgBlobTop: {
    position: "absolute",
    top: -150,
    left: -90,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "#ff2ea6",
    opacity: 0.22,
  },
  bgBlobBottom: {
    position: "absolute",
    bottom: -180,
    right: -120,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: "#26c7ff",
    opacity: 0.2,
  },
  container: {
    paddingHorizontal: 14,
    paddingBottom: 140,
    paddingTop: 8,
    gap: 12,
  },
  panelHeader: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#332a64",
    backgroundColor: "rgba(11, 6, 28, 0.92)",
    padding: 12,
    gap: 12,
    shadowColor: "#ff3aa8",
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  brandLogo: {
    width: "100%",
    height: 170,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#3b2f71",
  },
  headerTextBlock: {
    gap: 4,
  },
  title: {
    color: "#f6edff",
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  subtitle: {
    marginTop: 3,
    color: "#89d0ff",
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  headerRowWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  serverBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#5f4f96",
    backgroundColor: "rgba(45, 35, 84, 0.7)",
    color: "#e8dcff",
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "700",
  },
  statusPill: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#24d8ff",
    backgroundColor: "rgba(36, 216, 255, 0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusPillError: {
    borderColor: "#ff4f9f",
    backgroundColor: "rgba(255, 79, 159, 0.15)",
  },
  statusText: {
    color: "#deffff",
    fontSize: 12,
    fontWeight: "700",
  },
  tabRow: {
    flexDirection: "row",
    gap: 8,
  },
  tabButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4a3d84",
    backgroundColor: "rgba(21, 14, 44, 0.94)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  tabButtonCompact: {
    minWidth: 88,
  },
  tabButtonOn: {
    borderColor: "#ff8ad2",
    backgroundColor: "rgba(255, 46, 166, 0.22)",
  },
  tabButtonText: {
    color: "#a9d7ff",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  tabButtonTextOn: {
    color: "#ffe7f8",
  },
  navCompactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  navMenuButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4a3d84",
    backgroundColor: "rgba(21, 14, 44, 0.94)",
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 86,
    alignItems: "center",
    justifyContent: "center",
  },
  navMenuButtonText: {
    color: "#a9d7ff",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  navCompactTitle: {
    color: "#e4d8ff",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  navDrawerRoot: {
    flex: 1,
    flexDirection: "row",
  },
  navDrawerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(3, 2, 10, 0.72)",
  },
  navDrawerPanel: {
    width: "78%",
    maxWidth: 320,
    borderRightWidth: 1,
    borderColor: "#392d70",
    backgroundColor: "rgba(10, 6, 27, 0.98)",
    paddingHorizontal: 14,
    paddingVertical: 18,
    gap: 12,
  },
  navDrawerTitle: {
    color: "#9ad4ff",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    fontWeight: "700",
  },
  navDrawerList: {
    gap: 8,
  },
  navDrawerItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#47377e",
    backgroundColor: "rgba(24, 16, 49, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  navDrawerItemActive: {
    borderColor: "#ff56b2",
    backgroundColor: "rgba(255, 86, 178, 0.18)",
  },
  navDrawerItemText: {
    color: "#aad6ff",
    fontSize: 13,
    fontWeight: "700",
  },
  navDrawerItemTextActive: {
    color: "#ffe0f5",
  },
  panel: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#30265f",
    backgroundColor: "rgba(10, 7, 26, 0.9)",
    padding: 12,
    gap: 10,
  },
  panelLabel: {
    color: "#9ad4ff",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.9,
    marginBottom: 2,
    fontWeight: "700",
  },
  serverTitle: {
    color: "#ffd5f1",
    fontSize: 15,
    fontWeight: "800",
  },
  serverSubtitle: {
    color: "#a7cfff",
    fontSize: 12,
    flexShrink: 1,
  },
  serverListWrap: {
    gap: 8,
  },
  serverCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#44377a",
    backgroundColor: "rgba(18, 12, 40, 0.95)",
    padding: 10,
    gap: 8,
  },
  serverCardActive: {
    borderColor: "#2fd4ff",
    backgroundColor: "rgba(12, 25, 48, 0.88)",
  },
  serverCardHeader: {
    gap: 2,
  },
  serverName: {
    color: "#f4dfff",
    fontSize: 13,
    fontWeight: "800",
  },
  serverUrl: {
    color: "#93c8f7",
    fontSize: 11,
  },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3a2d71",
    backgroundColor: "rgba(14, 10, 34, 0.92)",
    color: "#f3ebff",
    paddingHorizontal: 11,
    paddingVertical: 10,
    fontSize: 15,
  },
  serverFiltersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  serverFilterInput: {
    flexGrow: 1,
    minWidth: 120,
  },
  tailInput: {
    minWidth: 84,
    textAlign: "center",
    paddingVertical: 8,
  },
  multilineInput: {
    minHeight: 86,
    textAlignVertical: "top",
  },
  modalInput: {
    minHeight: 110,
  },
  rowInlineSpace: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowInlineSpaceWrap: {
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  switchLabel: {
    color: "#a6cfff",
    fontSize: 13,
    fontWeight: "600",
  },
  buttonPrimary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ff8ad2",
    paddingVertical: 11,
    paddingHorizontal: 12,
    backgroundColor: "#ff2ea6",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPrimaryText: {
    color: "#fff6fc",
    fontWeight: "800",
    fontSize: 14,
  },
  buttonGhost: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4a3d84",
    paddingVertical: 11,
    paddingHorizontal: 12,
    backgroundColor: "rgba(21, 14, 44, 0.94)",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonGhostText: {
    color: "#a9d7ff",
    fontWeight: "700",
    fontSize: 13,
  },
  flexButton: {
    flex: 1,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  formDivider: {
    height: 1,
    backgroundColor: "#3c316d",
    marginVertical: 4,
  },
  modeRow: {
    flexDirection: "row",
    gap: 8,
  },
  modeButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4a3d84",
    backgroundColor: "rgba(21, 14, 44, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  modeButtonOn: {
    borderColor: "#27d9ff",
    backgroundColor: "rgba(39, 217, 255, 0.16)",
  },
  modeButtonText: {
    color: "#a9d7ff",
    fontSize: 12,
    fontWeight: "700",
  },
  modeButtonTextOn: {
    color: "#defbff",
  },
  chipRow: {
    gap: 8,
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#47377e",
    backgroundColor: "rgba(24, 16, 49, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipActive: {
    borderColor: "#ff56b2",
    backgroundColor: "rgba(255, 86, 178, 0.18)",
  },
  chipText: {
    color: "#aad6ff",
    fontSize: 12,
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#ffe0f5",
  },
  serverRail: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderColor: "#1a1440",
    backgroundColor: "rgba(6, 3, 18, 0.95)",
    borderRadius: 12,
  },
  serverRailGroupCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2e245a",
    backgroundColor: "rgba(18, 12, 37, 0.92)",
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginRight: 8,
  },
  serverRailGroupCardCompact: {
    marginRight: 0,
    marginBottom: 8,
    width: "100%",
  },
  serverRailGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
    gap: 8,
  },
  serverRailGroupHeaderAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  serverRailGroupLabel: {
    color: "#7f7aa8",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  serverRailGroupToggle: {
    color: "#66d7ff",
    fontSize: 10,
    fontWeight: "700",
  },
  serverRailGroupCount: {
    color: "#96b8de",
    fontSize: 10,
    fontWeight: "800",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#3b2d73",
    backgroundColor: "rgba(45, 32, 92, 0.7)",
    paddingHorizontal: 7,
    paddingVertical: 2,
    overflow: "hidden",
  },
  serverRailGroupUnreadBadge: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#ff8c42",
  },
  serverRailGroupSummary: {
    color: "#8ca8d7",
    fontSize: 10,
    fontWeight: "600",
    marginBottom: 2,
  },
  serverRailVmTypeRow: {
    gap: 5,
    marginBottom: 5,
  },
  serverRailVmTypeLabel: {
    color: "#8ca8d7",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  serverRailVmTypeChips: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  serverRailVmTypeListCompact: {
    gap: 6,
    alignItems: "flex-start",
  },
  serverRailChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#342868",
    backgroundColor: "rgba(24, 16, 49, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  serverRailChipCompact: {
    marginBottom: 6,
    maxWidth: "100%",
    flexShrink: 1,
  },
  serverRailChipFocused: {
    borderColor: "#0ea8c8",
    backgroundColor: "rgba(14, 168, 200, 0.12)",
  },
  serverRailDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  serverRailDotConnected: {
    backgroundColor: "#22d68a",
  },
  serverRailDotConnecting: {
    backgroundColor: "#f5a623",
  },
  serverRailDotDisconnected: {
    backgroundColor: "#ff4466",
  },
  serverRailDotInactive: {
    backgroundColor: "#444444",
  },
  serverRailName: {
    color: "#aad6ff",
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 100,
  },
  serverRailUnreadBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ff8c42",
  },
  serverRailCompactList: {
    gap: 0,
    width: "100%",
    alignSelf: "stretch",
  },
  serverPoolSummary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2a2350",
    backgroundColor: "rgba(8, 6, 24, 0.92)",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  serverPoolSummaryMetrics: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
  },
  serverPoolSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  serverPoolSummaryStack: {
    gap: 8,
  },
  serverPoolSummaryActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  serverPoolSummaryModes: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  serverPoolSummaryText: {
    color: "#9fcfff",
    fontSize: 11,
    fontWeight: "700",
  },
  terminalCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#342868",
    backgroundColor: "rgba(8, 6, 22, 0.95)",
    padding: 10,
    gap: 8,
    marginBottom: 8,
  },
  terminalHeader: {
    gap: 8,
  },
  terminalNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  terminalName: {
    color: "#ffd5f1",
    fontSize: 13,
    fontWeight: "800",
    flex: 1,
  },
  pillGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  modePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    overflow: "hidden",
  },
  modePillAi: {
    color: "#fff0f9",
    borderColor: "#ff6abf",
    backgroundColor: "rgba(255, 106, 191, 0.2)",
  },
  modePillShell: {
    color: "#defbff",
    borderColor: "#27d9ff",
    backgroundColor: "rgba(39, 217, 255, 0.16)",
  },
  livePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    overflow: "hidden",
  },
  livePillOn: {
    color: "#d5fffb",
    borderColor: "#27d9ff",
    backgroundColor: "rgba(39, 217, 255, 0.16)",
  },
  livePillWarn: {
    color: "#fff3d2",
    borderColor: "#ffc75a",
    backgroundColor: "rgba(255, 199, 90, 0.2)",
  },
  livePillOff: {
    color: "#ffdff4",
    borderColor: "#b66da0",
    backgroundColor: "rgba(182, 109, 160, 0.16)",
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  liveDotGreen: {
    backgroundColor: "#23f7be",
  },
  liveDotYellow: {
    backgroundColor: "#ffc75a",
  },
  liveDotRed: {
    backgroundColor: "#ff6ca6",
  },
  actionsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  actionButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#4b3f86",
    backgroundColor: "rgba(21, 14, 45, 0.95)",
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  actionButtonText: {
    color: "#9fd4ff",
    fontSize: 11,
    fontWeight: "700",
  },
  actionDangerButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ff5fae",
    backgroundColor: "rgba(255, 95, 174, 0.18)",
    paddingHorizontal: 9,
    paddingVertical: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  actionDangerText: {
    color: "#ffd4ee",
    fontSize: 11,
    fontWeight: "800",
  },
  terminalView: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#2fd4ff",
    backgroundColor: "#02010a",
    minHeight: 230,
    maxHeight: 360,
    padding: 9,
  },
  modalTerminalView: {
    flex: 1,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#2fd4ff",
    backgroundColor: "#02010a",
    padding: 10,
  },
  terminalText: {
    color: "#efe8ff",
    fontSize: 13,
    lineHeight: 18,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  modalHeader: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#35296b",
    backgroundColor: "rgba(12, 8, 30, 0.96)",
    padding: 10,
    gap: 8,
  },
  modalTitle: {
    color: "#f3dfff",
    fontSize: 15,
    fontWeight: "800",
  },
  keyboardBarContainer: {
    minHeight: 44,
    borderTopWidth: 1,
    borderColor: "#342868",
    backgroundColor: "rgba(12, 8, 32, 0.98)",
    borderRadius: 10,
    paddingVertical: 5,
    paddingHorizontal: 6,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  keyboardBarTabs: {
    width: 30,
    gap: 5,
    alignItems: "center",
  },
  keyboardBarTab: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#342868",
    backgroundColor: "rgba(16, 10, 36, 0.94)",
  },
  keyboardBarTabActive: {
    borderColor: "#0ea8c8",
    backgroundColor: "rgba(14, 168, 200, 0.15)",
  },
  keyboardBarTabText: {
    color: "#aad6ff",
    fontSize: 12,
    fontWeight: "700",
  },
  keyboardBarLayersViewport: {
    flex: 1,
    overflow: "hidden",
  },
  keyboardBarAnimatedTrack: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  keyboardBarScrollContent: {
    gap: 6,
    alignItems: "center",
    paddingRight: 10,
    minHeight: 34,
  },
  keyboardBarKeyButton: {
    minWidth: 38,
    height: 34,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#47377e",
    backgroundColor: "rgba(24, 16, 49, 0.95)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  keyboardBarKeyButtonActive: {
    borderColor: "#ff56b2",
    backgroundColor: "rgba(255, 86, 178, 0.18)",
  },
  keyboardBarKeyButtonLocked: {
    borderColor: "#ff56b2",
    backgroundColor: "rgba(255, 86, 178, 0.35)",
  },
  keyboardBarKeyText: {
    color: "#aad6ff",
    fontSize: 11,
    fontWeight: "700",
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  glassesHudStatus: {
    color: "#c2eeff",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  glassesRoutePanel: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#2c4a79",
    backgroundColor: "rgba(3, 8, 20, 0.98)",
    padding: 12,
    gap: 10,
    minHeight: 620,
  },
  glassesRouteHeader: {
    borderRadius: 14,
    borderWidth: 1,
    backgroundColor: "rgba(5, 11, 24, 0.96)",
    padding: 10,
    gap: 8,
  },
  glassesRouteTitle: {
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  glassesRouteExit: {
    minWidth: 88,
  },
  glassesRouteTerminalFrame: {
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: "#010108",
    minHeight: 270,
    maxHeight: 420,
    overflow: "hidden",
  },
  glassesRouteTerminalScroll: {
    flex: 1,
    padding: 10,
  },
  glassesRouteControls: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2d4871",
    backgroundColor: "rgba(4, 12, 24, 0.94)",
    padding: 10,
    gap: 8,
  },
  glassesRouteActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  glassesRouteButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4b6b9b",
    backgroundColor: "rgba(18, 31, 58, 0.96)",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  glassesRouteButtonText: {
    color: "#d1ecff",
    fontSize: 14,
    fontWeight: "700",
  },
  glassesRoutePrimary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#40d9ff",
    backgroundColor: "#0f7ea0",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  glassesRoutePrimaryText: {
    color: "#e8f9ff",
    fontSize: 14,
    fontWeight: "800",
  },
  glassesSpatialHeader: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
  },
  glassesSpatialSettings: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2d4871",
    backgroundColor: "rgba(4, 12, 24, 0.94)",
    padding: 10,
    gap: 8,
  },
  glassesSpatialSettingsHidden: {
    display: "none",
  },
  spatialLayout: {
    gap: 8,
  },
  spatialLayoutFullscreen: {
    minHeight: 320,
  },
  spatialLayoutEdgeRow: {
    minHeight: 86,
  },
  spatialLayoutMiddle: {
    flexDirection: "row",
    gap: 8,
    minHeight: 220,
  },
  spatialLayoutWing: {
    flex: 0.85,
  },
  spatialLayoutCore: {
    flex: 1.6,
  },
  spatialPanel: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3f5c89",
    backgroundColor: "rgba(6, 13, 28, 0.96)",
    overflow: "hidden",
    minHeight: 86,
  },
  spatialPanelFullscreen: {
    minHeight: 320,
  },
  spatialPanelCenter: {
    minHeight: 220,
  },
  spatialPanelSide: {
    minHeight: 220,
  },
  spatialPanelEdge: {
    minHeight: 86,
  },
  spatialPanelFocused: {
    borderColor: "#3dd7ff",
    backgroundColor: "rgba(13, 31, 60, 0.96)",
  },
  spatialPanelEmpty: {
    borderStyle: "dashed",
    borderColor: "#314665",
    backgroundColor: "rgba(2, 8, 18, 0.62)",
  },
  spatialPanelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderColor: "#2f4668",
    gap: 6,
  },
  spatialPanelHeaderMeta: {
    flex: 1,
    gap: 1,
  },
  spatialPanelServer: {
    color: "#8fd6ff",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  spatialPanelSession: {
    color: "#e8f8ff",
    fontSize: 11,
    fontWeight: "700",
  },
  spatialPanelHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  spatialPanelAction: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4b6b9b",
    backgroundColor: "rgba(18, 31, 58, 0.96)",
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  spatialPanelActionText: {
    color: "#d1ecff",
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 12,
  },
  spatialPanelOutput: {
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  vrRuntimeStatsRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  vrRuntimeActionRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  vrRuntimeInputCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2c4c73",
    backgroundColor: "rgba(10, 17, 34, 0.92)",
    padding: 10,
    gap: 8,
  },
  vrRuntimeHudStatus: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#356291",
    backgroundColor: "rgba(17, 31, 58, 0.92)",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  vrRuntimePanelList: {
    gap: 10,
  },
  vrRuntimePanelCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#334f76",
    backgroundColor: "rgba(7, 13, 30, 0.96)",
    padding: 10,
    gap: 8,
  },
  vrRuntimePanelCardFocused: {
    borderColor: "#3fd8ff",
    backgroundColor: "rgba(10, 25, 52, 0.96)",
  },
  vrRuntimePanelOutput: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1d3451",
    backgroundColor: "rgba(4, 8, 20, 0.96)",
    paddingHorizontal: 8,
    paddingVertical: 7,
    color: "#cbecff",
    fontSize: 12,
    lineHeight: 16,
    fontFamily: "Courier",
  },
  emptyText: {
    color: "#8cb6db",
    fontSize: 13,
  },
  overlayBackdrop: {
    flex: 1,
    backgroundColor: "rgba(2, 1, 10, 0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  overlayCard: {
    width: "100%",
    maxWidth: 520,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#3a2d71",
    backgroundColor: "rgba(11, 8, 30, 0.98)",
    padding: 14,
    gap: 10,
  },
  centeredWrap: {
    flex: 1,
    justifyContent: "center",
    padding: 16,
  },
  qrWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  splitRow: {
    flexDirection: "row",
    gap: 12,
  },
  splitLeft: {
    width: 320,
    gap: 12,
  },
  splitRight: {
    flex: 1,
  },
});
