import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#070b17",
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: "#050111",
    padding: 12,
    gap: 10,
  },
  flex: {
    flex: 1,
  },
  bgBlobTop: {
    position: "absolute",
    top: -150,
    left: -90,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "#ff2ea6",
    opacity: 0.22,
  },
  bgBlobBottom: {
    position: "absolute",
    bottom: -180,
    right: -120,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: "#26c7ff",
    opacity: 0.2,
  },
  shellBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#070b17",
  },
  shellBackdropRibbon: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: 104,
    backgroundColor: "rgba(128, 110, 216, 0.16)",
  },
  shellBackdropRibbonGlow: {
    position: "absolute",
    top: 44,
    left: -42,
    width: 220,
    height: 420,
    borderRadius: 110,
    backgroundColor: "rgba(152, 116, 255, 0.13)",
    transform: [{ rotate: "-12deg" }],
  },
  shellBackdropTopGlow: {
    position: "absolute",
    top: -120,
    right: -70,
    width: 320,
    height: 220,
    borderRadius: 120,
    backgroundColor: "rgba(54, 212, 255, 0.13)",
    transform: [{ rotate: "-10deg" }],
  },
  shellBackdropOrb: {
    position: "absolute",
    right: -150,
    bottom: 60,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: "rgba(29, 147, 255, 0.11)",
  },
  container: {
    paddingHorizontal: 18,
    paddingBottom: 42,
    paddingTop: 14,
    gap: 18,
  },
  containerGrow: {
    flexGrow: 1,
  },
  containerWithBottomDock: {
    paddingBottom: 150,
  },
  panelHeader: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#332a64",
    backgroundColor: "rgba(11, 6, 28, 0.92)",
    padding: 12,
    gap: 12,
    shadowColor: "#ff3aa8",
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  appTopBar: {
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderColor: "rgba(120, 130, 170, 0.2)",
    backgroundColor: "transparent",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  appTopBarLogo: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: 0,
  },
  appTopBarMeta: {
    flex: 1,
    gap: 1,
  },
  appTopBarMetaCompact: {
    alignItems: "flex-end",
    gap: 5,
    maxWidth: "45%",
  },
  appTopBarTitle: {
    color: "#f6edff",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  appTopBarSubtitle: {
    color: "#89d0ff",
    fontSize: 11,
    fontWeight: "700",
  },
  appTopBarRoutePill: {
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "rgba(34, 48, 92, 0.35)",
    color: "#9fd4ff",
    fontSize: 10,
    fontWeight: "800",
    paddingHorizontal: 10,
    paddingVertical: 4,
    overflow: "hidden",
  },
  brandLogo: {
    width: "100%",
    height: 170,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#3b2f71",
  },
  headerTextBlock: {
    gap: 4,
  },
  title: {
    color: "#f6edff",
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  subtitle: {
    marginTop: 3,
    color: "#89d0ff",
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  headerRowWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  serverBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#5f4f96",
    backgroundColor: "rgba(45, 35, 84, 0.7)",
    color: "#e8dcff",
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "700",
  },
  statusPill: {
    alignSelf: "flex-start",
    maxWidth: "100%",
    borderWidth: 1,
    borderColor: "#24d8ff",
    backgroundColor: "rgba(36, 216, 255, 0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusPillError: {
    borderColor: "#ff4f9f",
    backgroundColor: "rgba(255, 79, 159, 0.15)",
  },
  statusText: {
    color: "#deffff",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    flexShrink: 1,
  },
  tabRow: {
    flexDirection: "row",
    gap: 10,
  },
  tabButton: {
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "rgba(25, 32, 58, 0.22)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  tabButtonCompact: {
    minWidth: 88,
  },
  tabButtonOn: {
    backgroundColor: "rgba(55, 207, 255, 0.22)",
  },
  tabButtonText: {
    color: "#a9d7ff",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  tabButtonTextOn: {
    color: "#eaf7ff",
  },
  navCompactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  navMenuButton: {
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "rgba(25, 32, 58, 0.26)",
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 86,
    alignItems: "center",
    justifyContent: "center",
  },
  navMenuButtonText: {
    color: "#a9d7ff",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  navModeButton: {
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "rgba(32, 41, 72, 0.35)",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  navModeButtonText: {
    color: "#9ad4ff",
    fontSize: 12,
    fontWeight: "700",
  },
  navCompactTitle: {
    color: "#e4d8ff",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  bottomNavDock: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 10,
    zIndex: 50,
  },
  bottomQuickNav: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 20,
    borderWidth: 0,
    backgroundColor: "rgba(13, 16, 28, 0.88)",
    padding: 9,
    shadowColor: "#04050c",
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  bottomQuickNavButton: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
    paddingHorizontal: 6,
  },
  bottomQuickNavButtonActive: {
    backgroundColor: "rgba(55, 207, 255, 0.2)",
  },
  bottomQuickNavButtonText: {
    color: "#a9d7ff",
    fontSize: 11,
    fontWeight: "700",
  },
  bottomQuickNavButtonTextActive: {
    color: "#eaf7ff",
  },
  navDrawerRoot: {
    flex: 1,
    flexDirection: "row",
  },
  navDrawerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(3, 2, 10, 0.72)",
  },
  navDrawerPanel: {
    width: "78%",
    maxWidth: 320,
    borderRightWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.16)",
    backgroundColor: "rgba(17, 23, 44, 0.94)",
    paddingHorizontal: 16,
    paddingVertical: 20,
    gap: 12,
    shadowColor: "#02040b",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 6, height: 0 },
    elevation: 12,
  },
  navDrawerTitle: {
    color: "#9ad4ff",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    fontWeight: "700",
  },
  navDrawerList: {
    gap: 8,
  },
  navDrawerItem: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(140, 154, 214, 0.16)",
    backgroundColor: "rgba(41, 50, 85, 0.42)",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  navDrawerItemActive: {
    borderColor: "rgba(109, 213, 255, 0.3)",
    backgroundColor: "rgba(76, 141, 235, 0.22)",
  },
  navDrawerItemText: {
    color: "#aad6ff",
    fontSize: 13,
    fontWeight: "700",
  },
  navDrawerItemTextActive: {
    color: "#ffe0f5",
  },
  panel: {
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(132, 150, 220, 0.18)",
    backgroundColor: "rgba(22, 29, 54, 0.82)",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 14,
    shadowColor: "#02040b",
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
  },
  workspaceHero: {
    gap: 9,
    paddingVertical: 12,
  },
  workspaceHeroTitle: {
    color: "#f0ecff",
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  workspaceHeroSubtitle: {
    color: "#8fb6de",
    fontSize: 13,
    fontWeight: "600",
  },
  workspaceHeroActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  screenHeroCard: {
    minHeight: 168,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(137, 153, 224, 0.16)",
    backgroundColor: "rgba(25, 32, 58, 0.8)",
    overflow: "hidden",
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 14,
    shadowColor: "#01030b",
    shadowOpacity: 0.3,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 20 },
    elevation: 12,
  },
  screenHeroGlowA: {
    position: "absolute",
    top: -34,
    left: -24,
    width: 230,
    height: 150,
    borderRadius: 88,
    backgroundColor: "rgba(204, 95, 255, 0.22)",
    transform: [{ rotate: "-12deg" }],
  },
  screenHeroGlowB: {
    position: "absolute",
    right: -48,
    bottom: -42,
    width: 216,
    height: 150,
    borderRadius: 88,
    backgroundColor: "rgba(48, 212, 255, 0.18)",
    transform: [{ rotate: "10deg" }],
  },
  screenHeroEyebrow: {
    color: "#9aaee4",
    fontSize: 11,
    letterSpacing: 1.6,
    textTransform: "uppercase",
    fontWeight: "700",
  },
  screenHeroTitle: {
    color: "#f2f8ff",
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "800",
    maxWidth: "88%",
  },
  screenHeroSummary: {
    color: "#b8cae8",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
    maxWidth: "92%",
  },
  screenHeroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  screenHeroMetaCard: {
    minWidth: 110,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(149, 166, 227, 0.14)",
    backgroundColor: "rgba(13, 18, 35, 0.44)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  screenHeroMetaLabel: {
    color: "#8aa3d2",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  screenHeroMetaValue: {
    color: "#eef5ff",
    fontSize: 14,
    fontWeight: "800",
  },
  screenHeroToneCyan: {
    backgroundColor: "rgba(35, 56, 88, 0.78)",
  },
  screenHeroToneViolet: {
    backgroundColor: "rgba(53, 42, 91, 0.78)",
  },
  screenHeroTonePink: {
    backgroundColor: "rgba(74, 40, 90, 0.8)",
  },
  screenHeroToneSlate: {
    backgroundColor: "rgba(30, 39, 70, 0.8)",
  },
  panelLabel: {
    color: "#b6d9ff",
    fontSize: 14,
    textTransform: "none",
    letterSpacing: 0.2,
    marginBottom: 1,
    fontWeight: "800",
  },
  serverTitle: {
    color: "#ffd5f1",
    fontSize: 15,
    fontWeight: "800",
  },
  serverSubtitle: {
    color: "#b7cae8",
    fontSize: 13,
    flexShrink: 1,
  },
  serverListWrap: {
    gap: 8,
  },
  serverCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(135, 148, 214, 0.18)",
    backgroundColor: "rgba(30, 37, 68, 0.78)",
    paddingVertical: 14,
    paddingHorizontal: 15,
    gap: 12,
    shadowColor: "#02040b",
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 9,
  },
  serverCardActive: {
    borderColor: "rgba(103, 223, 255, 0.42)",
    backgroundColor: "rgba(19, 35, 60, 0.92)",
  },
  serverCardHeader: {
    gap: 2,
  },
  serverName: {
    color: "#f4dfff",
    fontSize: 13,
    fontWeight: "800",
  },
  serverUrl: {
    color: "#93c8f7",
    fontSize: 11,
  },
  input: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(107, 220, 255, 0.24)",
    backgroundColor: "rgba(28, 36, 65, 0.74)",
    color: "#f6f2ff",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    shadowColor: "#08253b",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  serverFiltersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  serverFilterInput: {
    flexGrow: 1,
    minWidth: 120,
  },
  tailInput: {
    minWidth: 84,
    textAlign: "center",
    paddingVertical: 8,
  },
  multilineInput: {
    minHeight: 86,
    textAlignVertical: "top",
  },
  modalInput: {
    minHeight: 110,
  },
  rowInlineSpace: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  rowInlineSpaceWrap: {
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  switchLabel: {
    color: "#a6cfff",
    fontSize: 13,
    fontWeight: "600",
  },
  buttonPrimary: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(108, 228, 255, 0.4)",
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "rgba(56, 178, 235, 0.24)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2db8ff",
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  buttonPrimaryText: {
    color: "#f3fdff",
    fontWeight: "800",
    fontSize: 14,
  },
  buttonGhost: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(132, 147, 210, 0.2)",
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: "rgba(31, 39, 69, 0.64)",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonGhostText: {
    color: "#cde8ff",
    fontWeight: "700",
    fontSize: 13,
  },
  flexButton: {
    flex: 1,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  formDivider: {
    height: 1,
    backgroundColor: "#3c316d",
    marginVertical: 4,
  },
  modeRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  modeButton: {
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "rgba(42, 56, 91, 0.25)",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  modeButtonOn: {
    backgroundColor: "rgba(55, 207, 255, 0.2)",
  },
  modeButtonText: {
    color: "#a9d7ff",
    fontSize: 12,
    fontWeight: "700",
  },
  modeButtonTextOn: {
    color: "#defbff",
  },
  chipRow: {
    gap: 8,
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.16)",
    backgroundColor: "rgba(34, 43, 72, 0.44)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipActive: {
    borderColor: "rgba(102, 224, 255, 0.34)",
    backgroundColor: "rgba(56, 147, 219, 0.22)",
  },
  chipText: {
    color: "#aad6ff",
    fontSize: 13,
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#eaf7ff",
  },
  serverRail: {
    paddingHorizontal: 0,
    paddingVertical: 2,
    borderBottomWidth: 0,
    backgroundColor: "transparent",
    borderRadius: 0,
  },
  serverRailGroupCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.14)",
    backgroundColor: "rgba(18, 24, 45, 0.68)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    shadowColor: "#02040b",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  serverRailGroupCardCompact: {
    marginRight: 0,
    marginBottom: 8,
    width: "100%",
  },
  serverRailGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
    gap: 8,
  },
  serverRailGroupHeaderAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  serverRailGroupLabel: {
    color: "#7f7aa8",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  serverRailGroupToggle: {
    color: "#66d7ff",
    fontSize: 10,
    fontWeight: "700",
  },
  serverRailGroupCount: {
    color: "#96b8de",
    fontSize: 10,
    fontWeight: "800",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#3b2d73",
    backgroundColor: "rgba(45, 32, 92, 0.7)",
    paddingHorizontal: 7,
    paddingVertical: 2,
    overflow: "hidden",
  },
  serverRailGroupUnreadBadge: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#ff8c42",
  },
  serverRailGroupSummary: {
    color: "#8ca8d7",
    fontSize: 10,
    fontWeight: "600",
    marginBottom: 2,
  },
  serverRailVmTypeRow: {
    gap: 5,
    marginBottom: 5,
  },
  serverRailVmTypeLabel: {
    color: "#8ca8d7",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  serverRailVmTypeChips: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  serverRailVmTypeListCompact: {
    gap: 6,
    alignItems: "flex-start",
  },
  serverRailChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.16)",
    backgroundColor: "rgba(43, 54, 88, 0.5)",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  serverRailChipCompact: {
    marginBottom: 6,
    maxWidth: "100%",
    flexShrink: 1,
  },
  serverRailChipFocused: {
    borderColor: "rgba(92, 214, 255, 0.34)",
    backgroundColor: "rgba(58, 145, 218, 0.22)",
  },
  serverRailDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  serverRailDotConnected: {
    backgroundColor: "#22d68a",
  },
  serverRailDotConnecting: {
    backgroundColor: "#f5a623",
  },
  serverRailDotDisconnected: {
    backgroundColor: "#ff4466",
  },
  serverRailDotInactive: {
    backgroundColor: "#444444",
  },
  serverRailName: {
    color: "#aad6ff",
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 100,
  },
  serverRailUnreadBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ff8c42",
  },
  serverRailCompactList: {
    gap: 0,
    width: "100%",
    alignSelf: "stretch",
  },
  serverPoolSummary: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.18)",
    backgroundColor: "rgba(18, 24, 45, 0.74)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
    shadowColor: "#02040b",
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  serverPoolSummaryMetrics: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
  },
  serverPoolSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  serverPoolSummaryStack: {
    gap: 8,
  },
  serverPoolSummaryActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  serverPoolSummaryModes: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  serverPoolSummaryText: {
    color: "#9fcfff",
    fontSize: 11,
    fontWeight: "700",
  },
  terminalCard: {
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.2)",
    backgroundColor: "rgba(16, 22, 43, 0.86)",
    paddingVertical: 15,
    paddingHorizontal: 15,
    gap: 12,
    marginBottom: 12,
    shadowColor: "#02040b",
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  terminalHeader: {
    gap: 8,
  },
  terminalNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  terminalName: {
    color: "#f8dcff",
    fontSize: 14,
    fontWeight: "800",
    flex: 1,
  },
  pillGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  modePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    overflow: "hidden",
  },
  modePillAi: {
    color: "#fff0f9",
    borderColor: "#ff6abf",
    backgroundColor: "rgba(255, 106, 191, 0.2)",
  },
  modePillShell: {
    color: "#defbff",
    borderColor: "#27d9ff",
    backgroundColor: "rgba(39, 217, 255, 0.16)",
  },
  livePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    overflow: "hidden",
  },
  livePillOn: {
    color: "#d5fffb",
    borderColor: "#27d9ff",
    backgroundColor: "rgba(39, 217, 255, 0.16)",
  },
  livePillWarn: {
    color: "#fff3d2",
    borderColor: "#ffc75a",
    backgroundColor: "rgba(255, 199, 90, 0.2)",
  },
  livePillOff: {
    color: "#ffdff4",
    borderColor: "#b66da0",
    backgroundColor: "rgba(182, 109, 160, 0.16)",
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  liveDotGreen: {
    backgroundColor: "#23f7be",
  },
  liveDotYellow: {
    backgroundColor: "#ffc75a",
  },
  liveDotRed: {
    backgroundColor: "#ff6ca6",
  },
  actionsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  actionButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(132, 148, 212, 0.18)",
    backgroundColor: "rgba(35, 43, 72, 0.54)",
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  actionButtonText: {
    color: "#cce7ff",
    fontSize: 12,
    fontWeight: "700",
  },
  actionDangerButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255, 118, 188, 0.24)",
    backgroundColor: "rgba(124, 40, 83, 0.32)",
    paddingHorizontal: 11,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  actionDangerText: {
    color: "#ffd4ee",
    fontSize: 11,
    fontWeight: "800",
  },
  terminalView: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(94, 223, 255, 0.5)",
    backgroundColor: "#02010a",
    minHeight: 230,
    maxHeight: 360,
    padding: 10,
  },
  modalTerminalView: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(94, 223, 255, 0.6)",
    backgroundColor: "#02010a",
    padding: 10,
  },
  terminalText: {
    color: "#efe8ff",
    fontSize: 13,
    lineHeight: 18,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  modalHeader: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#35296b",
    backgroundColor: "rgba(12, 8, 30, 0.96)",
    padding: 10,
    gap: 8,
  },
  modalTitle: {
    color: "#f3dfff",
    fontSize: 15,
    fontWeight: "800",
  },
  keyboardBarContainer: {
    minHeight: 44,
    borderTopWidth: 1,
    borderColor: "#342868",
    backgroundColor: "rgba(12, 8, 32, 0.98)",
    borderRadius: 10,
    paddingVertical: 5,
    paddingHorizontal: 6,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  keyboardBarTabs: {
    width: 30,
    gap: 5,
    alignItems: "center",
  },
  keyboardBarTab: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#342868",
    backgroundColor: "rgba(16, 10, 36, 0.94)",
  },
  keyboardBarTabActive: {
    borderColor: "#0ea8c8",
    backgroundColor: "rgba(14, 168, 200, 0.15)",
  },
  keyboardBarTabText: {
    color: "#aad6ff",
    fontSize: 12,
    fontWeight: "700",
  },
  keyboardBarLayersViewport: {
    flex: 1,
    overflow: "hidden",
  },
  keyboardBarAnimatedTrack: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  keyboardBarScrollContent: {
    gap: 6,
    alignItems: "center",
    paddingRight: 10,
    minHeight: 34,
  },
  keyboardBarKeyButton: {
    minWidth: 38,
    height: 34,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#47377e",
    backgroundColor: "rgba(24, 16, 49, 0.95)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  keyboardBarKeyButtonActive: {
    borderColor: "#ff56b2",
    backgroundColor: "rgba(255, 86, 178, 0.18)",
  },
  keyboardBarKeyButtonLocked: {
    borderColor: "#ff56b2",
    backgroundColor: "rgba(255, 86, 178, 0.35)",
  },
  keyboardBarKeyText: {
    color: "#aad6ff",
    fontSize: 11,
    fontWeight: "700",
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  glassesHudStatus: {
    color: "#c2eeff",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  glassesRoutePanel: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#2c4a79",
    backgroundColor: "rgba(3, 8, 20, 0.98)",
    padding: 12,
    gap: 10,
    minHeight: 620,
  },
  glassesRouteHeader: {
    borderRadius: 14,
    borderWidth: 1,
    backgroundColor: "rgba(5, 11, 24, 0.96)",
    padding: 10,
    gap: 8,
  },
  glassesRouteTitle: {
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  glassesRouteExit: {
    minWidth: 88,
  },
  glassesRouteTerminalFrame: {
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: "#010108",
    minHeight: 270,
    maxHeight: 420,
    overflow: "hidden",
  },
  glassesRouteTerminalScroll: {
    flex: 1,
    padding: 10,
  },
  glassesRouteControls: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2d4871",
    backgroundColor: "rgba(4, 12, 24, 0.94)",
    padding: 10,
    gap: 8,
  },
  glassesRouteActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  glassesRouteButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4b6b9b",
    backgroundColor: "rgba(18, 31, 58, 0.96)",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  glassesRouteButtonText: {
    color: "#d1ecff",
    fontSize: 14,
    fontWeight: "700",
  },
  glassesRoutePrimary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#40d9ff",
    backgroundColor: "#0f7ea0",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  glassesRoutePrimaryText: {
    color: "#e8f9ff",
    fontSize: 14,
    fontWeight: "800",
  },
  glassesSpatialHeader: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
  },
  glassesSpatialSettings: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2d4871",
    backgroundColor: "rgba(4, 12, 24, 0.94)",
    padding: 10,
    gap: 8,
  },
  glassesSpatialSettingsHidden: {
    display: "none",
  },
  spatialLayout: {
    gap: 8,
  },
  spatialLayoutFullscreen: {
    minHeight: 320,
  },
  spatialLayoutEdgeRow: {
    minHeight: 86,
  },
  spatialLayoutMiddle: {
    flexDirection: "row",
    gap: 8,
    minHeight: 220,
  },
  spatialLayoutWing: {
    flex: 0.85,
  },
  spatialLayoutCore: {
    flex: 1.6,
  },
  spatialPanel: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3f5c89",
    backgroundColor: "rgba(6, 13, 28, 0.96)",
    overflow: "hidden",
    minHeight: 86,
  },
  spatialPanelFullscreen: {
    minHeight: 320,
  },
  spatialPanelCenter: {
    minHeight: 220,
  },
  spatialPanelSide: {
    minHeight: 220,
  },
  spatialPanelEdge: {
    minHeight: 86,
  },
  spatialPanelFocused: {
    borderColor: "#3dd7ff",
    backgroundColor: "rgba(13, 31, 60, 0.96)",
  },
  spatialPanelEmpty: {
    borderStyle: "dashed",
    borderColor: "#314665",
    backgroundColor: "rgba(2, 8, 18, 0.62)",
  },
  spatialPanelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderColor: "#2f4668",
    gap: 6,
  },
  spatialPanelHeaderMeta: {
    flex: 1,
    gap: 1,
  },
  spatialPanelServer: {
    color: "#8fd6ff",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  spatialPanelSession: {
    color: "#e8f8ff",
    fontSize: 11,
    fontWeight: "700",
  },
  spatialPanelHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  spatialPanelAction: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4b6b9b",
    backgroundColor: "rgba(18, 31, 58, 0.96)",
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  spatialPanelActionText: {
    color: "#d1ecff",
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 12,
  },
  spatialPanelOutput: {
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  vrRuntimeStatsRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  vrRuntimeActionRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  vrRuntimeInputCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2c4c73",
    backgroundColor: "rgba(10, 17, 34, 0.92)",
    padding: 10,
    gap: 8,
  },
  vrRuntimeHudStatus: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#356291",
    backgroundColor: "rgba(17, 31, 58, 0.92)",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  vrRuntimePanelList: {
    gap: 10,
  },
  vrRuntimePanelCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#334f76",
    backgroundColor: "rgba(7, 13, 30, 0.96)",
    padding: 10,
    gap: 8,
  },
  vrRuntimePanelCardFocused: {
    borderColor: "#3fd8ff",
    backgroundColor: "rgba(10, 25, 52, 0.96)",
  },
  vrRuntimePanelOutput: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1d3451",
    backgroundColor: "rgba(4, 8, 20, 0.96)",
    paddingHorizontal: 8,
    paddingVertical: 7,
    color: "#cbecff",
    fontSize: 12,
    lineHeight: 16,
    fontFamily: "Courier",
  },
  launchIntroBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1200,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  launchIntroLogo: {
    width: 214,
    height: 214,
  },
  shellHeaderBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.18)",
    backgroundColor: "rgba(18, 24, 45, 0.68)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: "#02040b",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  shellHeaderMenuButton: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.18)",
    backgroundColor: "rgba(42, 52, 88, 0.5)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  shellHeaderMenuText: {
    color: "#c8e8ff",
    fontSize: 13,
    fontWeight: "700",
  },
  shellHeaderBrand: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  shellHeaderLogo: {
    width: 30,
    height: 30,
    borderRadius: 7,
  },
  shellHeaderBrandTitle: {
    color: "#eef4ff",
    fontSize: 15,
    fontWeight: "800",
  },
  shellHeaderBrandMeta: {
    color: "#89b7de",
    fontSize: 11,
    fontWeight: "700",
  },
  shellHeaderStatusWrap: {
    maxWidth: "27%",
    alignItems: "flex-end",
  },
  homeHubRoot: {
    flexGrow: 1,
    gap: 16,
    paddingVertical: 8,
  },
  homeHubHeaderSimple: {
    gap: 4,
  },
  homeHubHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
  },
  homeHubHeaderRowCompact: {
    flexDirection: "column",
  },
  homeHubEyebrow: {
    color: "#9aaee4",
    fontSize: 11,
    letterSpacing: 1.8,
    textTransform: "uppercase",
    fontWeight: "700",
  },
  homeHubStatus: {
    color: "#eef5ff",
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "800",
    maxWidth: "88%",
    marginTop: 4,
  },
  homeHubLead: {
    color: "#aebddf",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
    marginTop: 10,
    maxWidth: "92%",
  },
  homeHubHeaderBadge: {
    minWidth: 128,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(124, 154, 225, 0.16)",
    backgroundColor: "rgba(26, 33, 58, 0.72)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
    shadowColor: "#02040b",
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
  },
  homeHubHeaderBadgeLabel: {
    color: "#86a3d4",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  homeHubHeaderBadgeValue: {
    color: "#f3f7ff",
    fontSize: 16,
    fontWeight: "800",
  },
  homeHubShowcaseRow: {
    flexDirection: "row",
    gap: 16,
    alignItems: "stretch",
  },
  homeHubShowcaseColumn: {
    flexDirection: "column",
  },
  homeHubHeroCard: {
    minHeight: 336,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(137, 153, 224, 0.16)",
    backgroundColor: "rgba(25, 32, 58, 0.8)",
    overflow: "hidden",
    shadowColor: "#01030b",
    shadowOpacity: 0.3,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 20 },
    elevation: 12,
  },
  homeHubHeroCardCompact: {
    minHeight: 324,
  },
  homeHubHeroGlowA: {
    position: "absolute",
    top: -40,
    left: -10,
    width: 280,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(204, 95, 255, 0.24)",
    transform: [{ rotate: "-14deg" }],
  },
  homeHubHeroGlowB: {
    position: "absolute",
    right: -60,
    bottom: -40,
    width: 260,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(48, 212, 255, 0.18)",
    transform: [{ rotate: "10deg" }],
  },
  homeHubHeroContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    gap: 16,
    paddingHorizontal: 22,
    paddingVertical: 22,
  },
  homeHubHeroContentCompact: {
    flexDirection: "column",
  },
  homeHubBrandBlock: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 22,
  },
  homeHubHeroCopy: {
    flex: 1,
    justifyContent: "space-between",
    gap: 14,
    zIndex: 1,
  },
  homeHubHeroEyebrow: {
    color: "#b9d4ff",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  homeHubHeroTitle: {
    color: "#f7fbff",
    fontSize: 30,
    lineHeight: 35,
    fontWeight: "800",
    maxWidth: 360,
  },
  homeHubHeroSubtitle: {
    color: "#bad0ec",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
    maxWidth: 360,
  },
  homeHubHeroActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  homeHubHeroPrimaryButton: {
    borderRadius: 16,
    backgroundColor: "rgba(84, 208, 255, 0.24)",
    borderWidth: 1,
    borderColor: "rgba(121, 229, 255, 0.54)",
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#0fbfff",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  homeHubHeroPrimaryText: {
    color: "#effbff",
    fontSize: 14,
    fontWeight: "800",
  },
  homeHubHeroSecondaryButton: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(152, 170, 226, 0.2)",
    backgroundColor: "rgba(18, 24, 44, 0.56)",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  homeHubHeroSecondaryText: {
    color: "#dcebff",
    fontSize: 14,
    fontWeight: "700",
  },
  homeHubHeroStatRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  homeHubHeroStatPill: {
    borderRadius: 15,
    backgroundColor: "rgba(13, 18, 35, 0.44)",
    borderWidth: 1,
    borderColor: "rgba(149, 166, 227, 0.14)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
    minWidth: 112,
  },
  homeHubHeroStatLabel: {
    color: "#839bc8",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  homeHubHeroStatValue: {
    color: "#eef5ff",
    fontSize: 14,
    fontWeight: "800",
  },
  homeHubHeroVisual: {
    width: 208,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  homeHubHeroVisualCompact: {
    width: "100%",
    minHeight: 176,
  },
  homeHubAsideColumn: {
    flex: 0.86,
    gap: 14,
  },
  homeHubAsideColumnCompact: {
    flex: 1,
  },
  homeHubAsideCard: {
    flex: 1,
    minHeight: 132,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(141, 154, 216, 0.16)",
    backgroundColor: "rgba(35, 43, 72, 0.76)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    justifyContent: "flex-end",
    gap: 8,
    shadowColor: "#02040b",
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  homeHubAsideTitle: {
    color: "#f2f8ff",
    fontSize: 22,
    fontWeight: "800",
  },
  homeHubAsideCopy: {
    color: "#b7c8ea",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  homeHubSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 2,
  },
  homeHubSectionTitle: {
    color: "#ecf4ff",
    fontSize: 18,
    fontWeight: "800",
  },
  homeHubSectionMeta: {
    color: "#90a9d6",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  homeHubCardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  homeHubCardGridCompact: {
    flexDirection: "column",
    flexWrap: "nowrap",
  },
  homeHubLaunchCard: {
    width: "48%",
    minHeight: 152,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(141, 154, 216, 0.16)",
    backgroundColor: "rgba(37, 45, 74, 0.7)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    justifyContent: "flex-end",
    overflow: "hidden",
    shadowColor: "#02040b",
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  homeHubLaunchCardCompact: {
    width: "100%",
  },
  homeHubLaunchAccent: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 82,
    height: 82,
    borderRadius: 41,
    borderWidth: 1,
    borderColor: "rgba(111, 228, 255, 0.34)",
    backgroundColor: "rgba(16, 31, 52, 0.78)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#43d7ff",
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  homeHubLaunchAccentGlow: {
    position: "absolute",
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(103, 225, 255, 0.14)",
  },
  homeHubLaunchTitle: {
    color: "#eff7ff",
    fontSize: 24,
    fontWeight: "800",
  },
  homeHubLaunchSubtitle: {
    color: "#b6c8e6",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
    maxWidth: "90%",
    marginTop: 6,
  },
  homeHubFeedRow: {
    flexDirection: "row",
    gap: 14,
  },
  homeHubFeedRowCompact: {
    flexDirection: "column",
  },
  homeHubFeedCard: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(140, 152, 220, 0.14)",
    backgroundColor: "rgba(19, 24, 44, 0.7)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 8,
    shadowColor: "#02040b",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  homeHubFeedLabel: {
    color: "#8eb0dd",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.3,
  },
  homeHubFeedTitle: {
    color: "#ecf5ff",
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
  },
  homeHubFeedCopy: {
    color: "#adc1e0",
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "500",
  },
  homeHubToneCyan: {
    backgroundColor: "rgba(35, 56, 88, 0.76)",
  },
  homeHubToneViolet: {
    backgroundColor: "rgba(56, 43, 94, 0.76)",
  },
  homeHubTonePink: {
    backgroundColor: "rgba(78, 42, 92, 0.76)",
  },
  homeHubToneSlate: {
    backgroundColor: "rgba(34, 41, 70, 0.76)",
  },
  homeHubPlasmaWrap: {
    width: 200,
    height: 200,
    alignItems: "center",
    justifyContent: "center",
  },
  homeHubLogo: {
    width: "100%",
    height: "100%",
  },
  homeHubWordmark: {
    color: "#f2f7ff",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.3,
    marginTop: -2,
  },
  homeHubSummary: {
    color: "#bfd0eb",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
    textAlign: "center",
    maxWidth: 320,
    marginTop: 10,
  },
  homeHubFocusedServer: {
    color: "#97add3",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    marginTop: 12,
  },
  pageMenuRoot: {
    flex: 1,
    flexDirection: "row",
  },
  pageMenuBackdrop: {
    flex: 1,
    backgroundColor: "rgba(5, 7, 18, 0.6)",
  },
  pageMenuPanel: {
    width: "82%",
    maxWidth: 360,
    borderRightWidth: 1,
    borderColor: "rgba(141, 154, 216, 0.16)",
    backgroundColor: "rgba(13, 18, 36, 0.94)",
    paddingTop: 42,
    shadowColor: "#02040b",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 6, height: 0 },
    elevation: 12,
  },
  pageMenuScroll: {
    flex: 1,
  },
  pageMenuScrollContent: {
    paddingHorizontal: 18,
    paddingBottom: 18,
    gap: 16,
  },
  pageMenuHeroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(140, 154, 222, 0.16)",
    backgroundColor: "rgba(24, 31, 56, 0.82)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
    shadowColor: "#02040b",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  pageMenuEyebrow: {
    color: "#96ace0",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  pageMenuTitle: {
    color: "#f1f7ff",
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  pageMenuLead: {
    color: "#afc1e2",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
  },
  pageMenuHomeButton: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 123, 206, 0.46)",
    backgroundColor: "rgba(182, 74, 149, 0.18)",
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  pageMenuHomeText: {
    color: "#fff0fb",
    fontSize: 14,
    fontWeight: "800",
  },
  pageMenuHomeButtonFooter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  pageMenuSectionList: {
    gap: 12,
  },
  pageMenuSectionCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 122, 206, 0.18)",
    backgroundColor: "rgba(72, 34, 88, 0.6)",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 6,
    shadowColor: "#02040b",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  pageMenuSectionCardTitle: {
    color: "#eff7ff",
    fontSize: 19,
    fontWeight: "800",
  },
  pageMenuSectionCardDescription: {
    color: "#9fb8da",
    fontSize: 13,
    lineHeight: 19,
  },
  pageMenuSectionWrap: {
    gap: 12,
  },
  pageMenuBackButton: {
    alignSelf: "flex-start",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 175, 220, 0.22)",
    backgroundColor: "rgba(54, 25, 64, 0.7)",
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  pageMenuBackText: {
    color: "#ffe9f8",
    fontSize: 14,
    fontWeight: "700",
  },
  pageMenuSectionTitle: {
    color: "#eef6ff",
    fontSize: 23,
    fontWeight: "800",
  },
  pageMenuSectionDescription: {
    color: "#9db5d7",
    fontSize: 14,
    lineHeight: 20,
  },
  pageMenuSectionBody: {
    gap: 12,
  },
  pageMenuFooterActions: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderColor: "rgba(255, 121, 206, 0.12)",
    backgroundColor: "rgba(16, 12, 27, 0.72)",
  },
  pageMenuLogOffInline: {
    marginTop: -4,
    paddingTop: 0,
  },
  pageMenuLogOffButton: {
    alignSelf: "flex-start",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.18)",
    backgroundColor: "rgba(42, 52, 88, 0.5)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  pageMenuLogOffText: {
    color: "#c8e8ff",
    fontSize: 13,
    fontWeight: "700",
  },
  pageMenuActionGroup: {
    gap: 12,
  },
  pageMenuActionButton: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255, 126, 209, 0.16)",
    backgroundColor: "rgba(58, 29, 71, 0.9)",
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  pageMenuActionText: {
    color: "#fff1fb",
    fontSize: 15,
    fontWeight: "700",
  },
  pageMenuSwitchRow: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255, 126, 209, 0.16)",
    backgroundColor: "rgba(58, 29, 71, 0.9)",
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  pageMenuSwitchLabel: {
    color: "#fff1fb",
    fontSize: 13,
    fontWeight: "600",
    flex: 1,
  },
  pageMenuStepperRow: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255, 126, 209, 0.16)",
    backgroundColor: "rgba(58, 29, 71, 0.9)",
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  pageMenuStepperButtons: {
    flexDirection: "row",
    gap: 8,
  },
  pageMenuStepperButton: {
    minWidth: 34,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "rgba(255, 158, 220, 0.5)",
    backgroundColor: "rgba(85, 42, 96, 0.86)",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  pageMenuStepperText: {
    color: "#fff1fb",
    fontSize: 16,
    fontWeight: "800",
  },
  emptyText: {
    color: "#8cb6db",
    fontSize: 13,
  },
  overlayBackdrop: {
    flex: 1,
    backgroundColor: "rgba(2, 1, 10, 0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  overlayCard: {
    width: "100%",
    maxWidth: 520,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(136, 148, 208, 0.16)",
    backgroundColor: "rgba(16, 21, 41, 0.94)",
    padding: 18,
    gap: 14,
    shadowColor: "#02040b",
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  controlCenterCard: {
    maxHeight: "86%",
  },
  controlCenterScroll: {
    maxHeight: 560,
  },
  controlCenterScrollContent: {
    paddingBottom: 12,
    gap: 10,
  },
  centeredWrap: {
    flex: 1,
    justifyContent: "center",
    padding: 16,
  },
  qrWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  splitRow: {
    flexDirection: "row",
    gap: 12,
  },
  splitLeft: {
    width: 320,
    gap: 12,
  },
  splitRight: {
    flex: 1,
  },
  novaOverlayRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 120,
  },
  novaFloatingButtonWrap: {
    position: "absolute",
    width: 56,
    height: 56,
  },
  novaFloatingButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(77, 214, 255, 0.74)",
    backgroundColor: "rgba(10, 16, 34, 0.94)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#19cfff",
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 12,
  },
  novaFloatingButtonImageWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(108, 220, 255, 0.62)",
    backgroundColor: "rgba(8, 14, 26, 0.86)",
  },
  novaFloatingButtonImage: {
    width: "100%",
    height: "100%",
  },
  novaFloatingButtonActive: {
    borderColor: "rgba(255, 101, 200, 0.82)",
  },
  novaFloatingButtonRecording: {
    backgroundColor: "rgba(72, 18, 52, 0.96)",
    borderColor: "rgba(255, 101, 200, 0.88)",
  },
  novaOverlayPanel: {
    position: "absolute",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(83, 114, 190, 0.42)",
    backgroundColor: "rgba(7, 10, 21, 0.98)",
    padding: 14,
    gap: 12,
    shadowColor: "#040712",
    shadowOpacity: 0.34,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  novaOverlayPanelFullscreen: {
    position: "absolute",
    left: 8,
    right: 8,
    top: 8,
    bottom: 8,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(83, 114, 190, 0.42)",
    backgroundColor: "rgba(7, 10, 21, 0.985)",
    padding: 14,
    gap: 12,
  },
  novaOverlayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  novaOverlayHeaderMeta: {
    flex: 1,
    gap: 2,
  },
  novaOverlayTitle: {
    color: "#f2f6ff",
    fontSize: 20,
    fontWeight: "800",
  },
  novaOverlaySubtitle: {
    color: "#8fcfff",
    fontSize: 12,
    fontWeight: "600",
  },
  novaOverlayHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  novaOverlayToggleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(101, 127, 188, 0.5)",
    backgroundColor: "rgba(22, 31, 58, 0.78)",
    paddingLeft: 10,
    paddingRight: 6,
    paddingVertical: 5,
  },
  novaOverlayToggleLabel: {
    color: "#d9f5ff",
    fontSize: 12,
    fontWeight: "700",
  },
  novaOverlayHeaderButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(101, 127, 188, 0.5)",
    backgroundColor: "rgba(22, 31, 58, 0.78)",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  novaOverlayHeaderButtonActive: {
    borderColor: "rgba(55, 214, 255, 0.75)",
    backgroundColor: "rgba(25, 94, 121, 0.44)",
  },
  novaOverlayHeaderButtonText: {
    color: "#d9f5ff",
    fontSize: 12,
    fontWeight: "700",
  },
  novaOverlayStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  novaOverlayHint: {
    color: "#8fb6d8",
    fontSize: 12,
    flex: 1,
  },
  novaInlineButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(67, 99, 168, 0.54)",
    backgroundColor: "rgba(17, 26, 48, 0.88)",
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  novaInlineButtonText: {
    color: "#d8ecff",
    fontSize: 12,
    fontWeight: "700",
  },
  novaOverlayError: {
    color: "#ff9db7",
    fontSize: 12,
    fontWeight: "700",
  },
  novaOverlayTranscript: {
    flex: 1,
    minHeight: 180,
    maxHeight: 540,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(75, 95, 148, 0.34)",
    backgroundColor: "rgba(10, 13, 27, 0.78)",
  },
  novaOverlayTranscriptContent: {
    padding: 12,
    gap: 10,
  },
  novaMessageBubble: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 5,
  },
  novaMessageBubbleAssistant: {
    borderColor: "rgba(90, 121, 185, 0.34)",
    backgroundColor: "rgba(19, 27, 50, 0.82)",
    alignSelf: "stretch",
  },
  novaMessageBubbleUser: {
    borderColor: "rgba(54, 206, 255, 0.38)",
    backgroundColor: "rgba(12, 50, 75, 0.68)",
    alignSelf: "stretch",
  },
  novaMessageRole: {
    color: "#9bd7ff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  novaMessageText: {
    color: "#edf4ff",
    fontSize: 14,
    lineHeight: 20,
  },
  novaOverlayComposer: {
    gap: 10,
  },
  novaComposerInput: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  novaOverlayComposerActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "wrap",
  },
  novaComposerButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(88, 120, 184, 0.52)",
    backgroundColor: "rgba(20, 27, 51, 0.92)",
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 88,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  novaComposerButtonPrimary: {
    borderColor: "rgba(54, 206, 255, 0.76)",
    backgroundColor: "rgba(16, 110, 143, 0.48)",
  },
  novaComposerButtonVoiceActive: {
    borderColor: "rgba(54, 206, 255, 0.76)",
    backgroundColor: "rgba(24, 86, 131, 0.5)",
  },
  novaComposerButtonRecording: {
    borderColor: "rgba(255, 112, 192, 0.82)",
    backgroundColor: "rgba(111, 31, 72, 0.82)",
  },
  novaComposerButtonText: {
    color: "#eff7ff",
    fontSize: 13,
    fontWeight: "800",
  },
  novaResizeHandle: {
    position: "absolute",
    right: 10,
    bottom: 10,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(84, 116, 189, 0.48)",
    backgroundColor: "rgba(19, 29, 56, 0.94)",
  },
});
